"""feat: update patient and caretaker profiles

Revision ID: 13aac6721dca
Revises: 46c4d29f2ad1
Create Date: 2026-03-08 21:52:58.807251
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13aac6721dca"
down_revision: str | None = "46c4d29f2ad1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("patients", "caretaker_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_constraint(op.f("patients_caretaker_id_fkey"), "patients", type_="foreignkey")
    op.create_foreign_key(None, "patients", "caretakers", ["caretaker_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("patients_caretaker_id_fkey"), "patients", type_="foreignkey")
    op.create_foreign_key(
        op.f("patients_caretaker_id_fkey"), "patients", "caretakers", ["caretaker_id"], ["id"], ondelete="RESTRICT"
    )
    op.alter_column("patients", "caretaker_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
