"""feat: initial_gait_analysis_schema

Revision ID: 44268ef266c0
Revises:
Create Date: 2026-03-06 13:44:29.065366
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44268ef266c0'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('caretaker', 'patient')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('caretakers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caretakers_user_id'), 'caretakers', ['user_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('caretaker_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caretaker_id'], ['caretakers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_caretaker_id'), 'patients', ['caretaker_id'], unique=False)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_table('daily_averages',
    sa.Column('daily_report_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_windows_analyzed', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_distance_m', sa.Float(), nullable=True),
    sa.Column('avg_max_gyr_ms', sa.Float(), nullable=True),
    sa.Column('avg_val_gyr_hs', sa.Float(), nullable=True),
    sa.Column('avg_swing_time', sa.Float(), nullable=True),
    sa.Column('avg_stance_time', sa.Float(), nullable=True),
    sa.Column('avg_stride_cv', sa.Float(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('daily_report_id')
    )
    op.create_index('ix_daily_averages_patient_date', 'daily_averages', ['patient_id', 'report_date'], unique=False)
    op.create_table('window_reports',
    sa.Column('window_report_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('gait_health', sa.String(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('max_gyr_ms', sa.Float(), nullable=True),
    sa.Column('val_gyr_hs', sa.Float(), nullable=True),
    sa.Column('swing_time', sa.Float(), nullable=True),
    sa.Column('stance_time', sa.Float(), nullable=True),
    sa.Column('stride_time', sa.Float(), nullable=True),
    sa.Column('stride_cv', sa.Float(), nullable=True),
    sa.Column('n_strides', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.CheckConstraint("gait_health IN ('NORMAL', 'ANOMALY_DETECTED')", name='ck_window_reports_gait_health'),
    sa.CheckConstraint("status IN ('CALIBRATING', 'MONITORING')", name='ck_window_reports_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('window_report_id')
    )
    op.create_index(op.f('ix_window_reports_patient_id'), 'window_reports', ['patient_id'], unique=False)
    op.create_index(op.f('ix_window_reports_timestamp'), 'window_reports', ['timestamp'], unique=False)
    op.create_table('anomaly_logs',
    sa.Column('anomaly_id', sa.String(), nullable=False),
    sa.Column('window_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('root_cause_feature', sa.String(), nullable=True),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('current_val', sa.Float(), nullable=True),
    sa.Column('normal_ref', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['window_reports.window_report_id'], ),
    sa.PrimaryKeyConstraint('anomaly_id')
    )
    op.create_index(op.f('ix_anomaly_logs_patient_id'), 'anomaly_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_anomaly_logs_timestamp'), 'anomaly_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_anomaly_logs_window_id'), 'anomaly_logs', ['window_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomaly_logs_window_id'), table_name='anomaly_logs')
    op.drop_index(op.f('ix_anomaly_logs_timestamp'), table_name='anomaly_logs')
    op.drop_index(op.f('ix_anomaly_logs_patient_id'), table_name='anomaly_logs')
    op.drop_table('anomaly_logs')
    op.drop_index(op.f('ix_window_reports_timestamp'), table_name='window_reports')
    op.drop_index(op.f('ix_window_reports_patient_id'), table_name='window_reports')
    op.drop_table('window_reports')
    op.drop_index('ix_daily_averages_patient_date', table_name='daily_averages')
    op.drop_table('daily_averages')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_caretaker_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_caretakers_user_id'), table_name='caretakers')
    op.drop_table('caretakers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
