"""feat: add_ondelete_restrict_to_reports

Revision ID: 46c4d29f2ad1
Revises: 44268ef266c0
Create Date: 2026-03-06 14:39:59.021590
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46c4d29f2ad1"
down_revision: str | None = "44268ef266c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("anomaly_logs_patient_id_fkey"), "anomaly_logs", type_="foreignkey")
    op.create_foreign_key(None, "anomaly_logs", "patients", ["patient_id"], ["id"], ondelete="RESTRICT")
    op.drop_index(op.f("ix_daily_averages_patient_date"), table_name="daily_averages")
    op.create_index("ix_daily_averages_patient_date", "daily_averages", ["patient_id", "report_date"], unique=True)
    op.alter_column("patients", "age", existing_type=sa.BIGINT(), type_=sa.Integer(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("patients", "age", existing_type=sa.Integer(), type_=sa.BIGINT(), existing_nullable=True)
    op.drop_index("ix_daily_averages_patient_date", table_name="daily_averages")
    op.create_index(
        op.f("ix_daily_averages_patient_date"), "daily_averages", ["patient_id", "report_date"], unique=False
    )
    op.drop_constraint(None, "anomaly_logs", type_="foreignkey")
    op.create_foreign_key(op.f("anomaly_logs_patient_id_fkey"), "anomaly_logs", "patients", ["patient_id"], ["id"])
    # ### end Alembic commands ###
