"""feat: add monthly and yearly avg

Revision ID: f39c2dac4f38
Revises: 736d554f1558
Create Date: 2026-03-18 05:52:41.392193
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f39c2dac4f38'
down_revision: str | None = '736d554f1558'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monthly_averages",
        sa.Column("monthly_report_id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.BigInteger(), nullable=False),
        sa.Column("report_month", sa.String(), nullable=False),
        sa.Column("total_windows_analyzed", sa.Integer(), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("total_calories", sa.Float(), nullable=True),
        sa.Column("total_distance_m", sa.Float(), nullable=True),
        sa.Column("avg_max_gyr_ms", sa.Float(), nullable=True),
        sa.Column("avg_val_gyr_hs", sa.Float(), nullable=True),
        sa.Column("avg_swing_time", sa.Float(), nullable=True),
        sa.Column("avg_stance_time", sa.Float(), nullable=True),
        sa.Column("avg_stride_cv", sa.Float(), nullable=True),
        sa.Column("anomaly_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("monthly_report_id"),
    )
    op.create_index("ix_monthly_averages_patient_month", "monthly_averages", ["patient_id", "report_month"], unique=True)

    op.create_table(
        "yearly_averages",
        sa.Column("yearly_report_id", sa.String(), nullable=False),
        sa.Column("patient_id", sa.BigInteger(), nullable=False),
        sa.Column("report_year", sa.Integer(), nullable=False),
        sa.Column("total_windows_analyzed", sa.Integer(), nullable=True),
        sa.Column("total_steps", sa.Integer(), nullable=True),
        sa.Column("total_calories", sa.Float(), nullable=True),
        sa.Column("total_distance_m", sa.Float(), nullable=True),
        sa.Column("avg_max_gyr_ms", sa.Float(), nullable=True),
        sa.Column("avg_val_gyr_hs", sa.Float(), nullable=True),
        sa.Column("avg_swing_time", sa.Float(), nullable=True),
        sa.Column("avg_stance_time", sa.Float(), nullable=True),
        sa.Column("avg_stride_cv", sa.Float(), nullable=True),
        sa.Column("anomaly_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("yearly_report_id"),
    )
    op.create_index("ix_yearly_averages_patient_year", "yearly_averages", ["patient_id", "report_year"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_yearly_averages_patient_year", table_name="yearly_averages")
    op.drop_table("yearly_averages")

    op.drop_index("ix_monthly_averages_patient_month", table_name="monthly_averages")
    op.drop_table("monthly_averages")
    # ### end Alembic commands ###
