"""fix_missing_weekly

Revision ID: fd5c388e2451
Revises: 157ad1d052bb
Create Date: 2026-03-19 09:41:41.581331
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd5c388e2451'
down_revision: str | None = '157ad1d052bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_averages',
    sa.Column('weekly_report_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('report_week', sa.String(), nullable=False),
    sa.Column('total_windows_analyzed', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=True),
    sa.Column('total_distance_m', sa.Float(), nullable=True),
    sa.Column('avg_max_gyr_ms', sa.Float(), nullable=True),
    sa.Column('avg_val_gyr_hs', sa.Float(), nullable=True),
    sa.Column('avg_swing_time', sa.Float(), nullable=True),
    sa.Column('avg_stance_time', sa.Float(), nullable=True),
    sa.Column('avg_stride_cv', sa.Float(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('weekly_report_id')
    )
    op.create_index('ix_weekly_averages_patient_week', 'weekly_averages', ['patient_id', 'report_week'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_averages_patient_week', table_name='weekly_averages')
    op.drop_table('weekly_averages')
    # ### end Alembic commands ###